name: Tests

on:
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'news/**'
      - '*.md'
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'news/**'
      - '*.md'

jobs:
  Testing:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.7, '3.10', '3.11']
        os: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Set up PDM
        uses: pdm-project/setup-pdm@main
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set Variables
        id: set_variables
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git config --global init.defaultBranch main

      - name: Install dependencies
        run: python -m pip install -U copier
      - name: Setup Tests(Unix)
        run: bash tests/setup.sh

        if: runner.os != 'Windows'
      - name: Setup Tests(Windows)
        run: ./tests/setup.ps1
        if: runner.os == 'Windows'
      - name: Run Tests
        run: |
          pdm use -f ${{ matrix.python-version }}
          pdm install -d
          pdm run test
        working-directory: ${{ github.workspace }}/tests/tmp
