name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - "*.md"
      - docs/**
  workflow_dispatch:

jobs:
  build-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.9
      - name: Build pages
        run: |
          pip install mkdocs mkdocs-material
          cd docs && mkdocs build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/site
